title: Mijn Project Titel
author: G29

repository:
  url: https://github.com/JanKawak/G29
  path_to_book: docs
  branch: main

html:
  baseurl: "/G29/"
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
