# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Welzijn
author: G29

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/JanKawak/G29
  path_to_book: .
  branch: main

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  show_navbar_depth: 1

  # Toggle knoppen voor code
  extra_footer: ""
  use_togglebutton: true

# Add launch buttons
launch_buttons:
  binderhub_url: ""
  colab_url: "https://colab.research.google.com"
  jupyterhub_url: ""

sphinx:
  extra_extensions:
    # This is to work around the bug of no syntax highlighting
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    togglebutton_hint: "Toon/verberg code"
    html_js_files:
      # This is for plotly to work
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
